name: build-and-lint

on:
  push:
    branches: ["main", "dev"]

  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: node setup
        uses: actions/setup-node@v3

        with:
          node-version: 20

      - name: Installing backend dependencies
        working-directory: server
        run: npm ci

      - name: Lint backend
        working-directory: server
        run: npm run lint

      - name: Installing frontend dependencies
        working-directory: client
        run: npm ci

      - name: Lint frontend
        working-directory: client
        run: npm run lint

      - name: build backend image
        run: docker build -t mern-backend ./server

      - name: build frontend image
        run: docker build -t mern-frontend ./client

  deploy:
    needs: build-and-lint
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: adding ec2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}


      - name: write ssh key 
        run: |
          echo "${EC2_KEY}" > ec2_key.pem
          chmod 600 ec2_key.pem

        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

      - name: deploy on ec2 (git pull + docker compose up -d --build )
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_APP_DIR: ${{ secrets.EC2_APP_DIR }}

        run: |
          ssh -i ec2_key.pem $EC2_USER@$EC2_HOST << EOF
            set -e 
            cd "${EC2_APP_DIR}"

            git fetch --all
            git reset --hard remote/origin

            docker compose up -d --build

            docker image prune -f 

            docker compose ps 
          EOF 